name: CI/CD for Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Choose your preferred OS (e.g., ubuntu-latest, windows-latest)

    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
